# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDownloadFinancialEN():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_downloadFinancialEN(self):
    # Test name: Download Financial EN
    # Step # | name | target | value | comment
    # 1 | open | https://demo.irplus.in.th/Listed/susco/finance_statement.asp |  | 
    self.driver.get("https://demo.irplus.in.th/Listed/susco/finance_statement.asp")
    # 2 | setWindowSize | 1936x1056 |  | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | linkText=EN |  | 
    self.driver.find_element(By.LINK_TEXT, "EN").click()
    # 4 | click | css=.finance_download_en |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 5 | storeWindowHandle | root |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".finance_download_en").click()
    # 6 | selectWindow | handle=${win3656} |  | 
    self.vars["win3656"] = self.wait_for_window(2000)
    # 7 | close |  |  | 
    self.vars["root"] = self.driver.current_window_handle
    # 8 | selectWindow | handle=${root} |  | 
    self.driver.switch_to.window(self.vars["win3656"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
  
