# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEmailAlertsSubscribeEN():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_emailAlertsSubscribeEN(self):
    # Test name: Email Alerts Subscribe EN
    # Step # | name | target | value | comment
    # 1 | open | https://demo.irplus.in.th/Listed/susco/email_alerts_subscribe.asp |  | 
    self.driver.get("https://demo.irplus.in.th/Listed/susco/email_alerts_subscribe.asp")
    # 2 | setWindowSize | 1936x1056 |  | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | linkText=EN |  | 
    self.driver.find_element(By.LINK_TEXT, "EN").click()
  
