# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestEmailAlertsUnsubscribeEN():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_emailAlertsUnsubscribeEN(self):
    # Test name: Email Alerts Unsubscribe EN
    # Step # | name | target | value | comment
    # 1 | open | https://demo.irplus.in.th/Listed/susco/email_alerts_unsubscribe.asp |  | 
    self.driver.get("https://demo.irplus.in.th/Listed/susco/email_alerts_unsubscribe.asp")
    # 2 | setWindowSize | 1936x1056 |  | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | linkText=EN |  | 
    self.driver.find_element(By.LINK_TEXT, "EN").click()
    # 4 | click | id=email |  | 
    self.driver.find_element(By.ID, "email").click()
    # 5 | type | id=email | Test@tt.tt | 
    self.driver.find_element(By.ID, "email").send_keys("Test@tt.tt")
    # 6 | selectFrame | index=0 |  | 
    self.driver.switch_to.frame(0)
    # 7 | click | id=recaptcha-anchor-label |  | 
    self.driver.find_element(By.ID, "recaptcha-anchor-label").click()
    # 8 | selectFrame | relative=parent |  | 
    self.driver.switch_to.default_content()
    # 9 | selectFrame | index=2 |  | 
    self.driver.switch_to.frame(2)
    # 10 | click | css=tr:nth-child(2) > .rc-imageselect-tile:nth-child(1) .rc-image-tile-33 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(2) > .rc-imageselect-tile:nth-child(1) .rc-image-tile-33").click()
    # 11 | click | css=tr:nth-child(1) > .rc-imageselect-tile:nth-child(2) .rc-image-tile-33 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(1) > .rc-imageselect-tile:nth-child(2) .rc-image-tile-33").click()
    # 12 | click | css=tr:nth-child(3) > .rc-imageselect-tile:nth-child(1) .rc-image-tile-33 |  | 
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(3) > .rc-imageselect-tile:nth-child(1) .rc-image-tile-33").click()
    # 13 | click | id=recaptcha-verify-button |  | 
    self.driver.find_element(By.ID, "recaptcha-verify-button").click()
    # 14 | selectFrame | relative=parent |  | 
    self.driver.switch_to.default_content()
    # 15 | click | css=.btn__title |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".btn__title").click()
  
