# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHomepageTH():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_homepageTH(self):
    # Test name: Homepage TH
    # Step # | name | target | value | comment
    # 1 | open | https://demo.irplus.in.th/Listed/susco/homepage.asp |  | 
    self.driver.get("https://demo.irplus.in.th/Listed/susco/homepage.asp")
    # 2 | setWindowSize | 1936x1056 |  | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 4 | click | linkText=TH |  | 
    self.driver.find_element(By.LINK_TEXT, "TH").click()
    # 5 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 6 | click | linkText=หน้าหลัก |  | 
    self.driver.find_element(By.LINK_TEXT, "หน้าหลัก").click()
    # 7 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 8 | click | id=slideout-bt |  | 
    self.driver.find_element(By.ID, "slideout-bt").click()
    # 9 | click | linkText=ยอมรับ |  | 
    self.driver.find_element(By.LINK_TEXT, "ยอมรับ").click()
    # 10 | click | id=two-tab |  | 
    self.driver.find_element(By.ID, "two-tab").click()
    # 11 | click | id=one-tab |  | 
    self.driver.find_element(By.ID, "one-tab").click()
    # 12 | click | css=.cover-promotion .text-right p |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".cover-promotion .text-right p").click()
    # 13 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    # 14 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 15 | click | css=.cover-news .text-right p |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".cover-news .text-right p").click()
    # 16 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    # 17 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
  
