# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestHomeTH28666():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def wait_for_window(self, timeout = 2):
    time.sleep(round(timeout / 1000))
    wh_now = self.driver.window_handles
    wh_then = self.vars["window_handles"]
    if len(wh_now) > len(wh_then):
      return set(wh_now).difference(set(wh_then)).pop()
  
  def test_homeTH28666(self):
    # Test name: Home TH 28/6/66
    # Step # | name | target | value | comment
    # 1 | open | https://demo.irplus.in.th/Listed/susco/homepage.asp |  | 
    self.driver.get("https://demo.irplus.in.th/Listed/susco/homepage.asp")
    # 2 | setWindowSize | 1936x1056 |  | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 4 | click | linkText=TH |  | 
    self.driver.find_element(By.LINK_TEXT, "TH").click()
    # 5 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 6 | click | linkText=นักลงทุนสัมพันธ์ |  | 
    self.driver.find_element(By.LINK_TEXT, "นักลงทุนสัมพันธ์").click()
    # 7 | click | linkText=หน้าหลักนักลงทุนสัมพันธ์ |  | 
    self.driver.find_element(By.LINK_TEXT, "หน้าหลักนักลงทุนสัมพันธ์").click()
    # 8 | click | id=slideout-bt |  | 
    self.driver.find_element(By.ID, "slideout-bt").click()
    # 9 | click | linkText=ยอมรับ |  | 
    self.driver.find_element(By.LINK_TEXT, "ยอมรับ").click()
    # 10 | click | css=p:nth-child(3) .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, "p:nth-child(3) .read-more").click()
    # 11 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    # 12 | click | css=.mb-4:nth-child(5) .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(5) .read-more").click()
    # 13 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    # 14 | click | css=.mb-4:nth-child(6) .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(6) .read-more").click()
    # 15 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    # 16 | click | css=.mb-4:nth-child(7) .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".mb-4:nth-child(7) .read-more").click()
    # 17 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    # 18 | click | css=.col-lg-6:nth-child(1) .d-inline-flex > .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-6:nth-child(1) .d-inline-flex > .read-more").click()
    # 19 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    # 20 | click | css=.col-lg-6:nth-child(2) > .text-right .d-inline-flex > .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-lg-6:nth-child(2) > .text-right .d-inline-flex > .read-more").click()
    # 21 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    # 22 | click | linkText=ราคาหลักทรัพย์ย้อนหลัง |  | 
    self.driver.find_element(By.LINK_TEXT, "ราคาหลักทรัพย์ย้อนหลัง").click()
    # 23 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    # 24 | click | linkText=เครื่องคำนวณการลงทุน |  | 
    self.driver.find_element(By.LINK_TEXT, "เครื่องคำนวณการลงทุน").click()
    # 25 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    # 26 | click | css=.more-FH .d-inline-flex > .read-more |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".more-FH .d-inline-flex > .read-more").click()
    # 27 | runScript | window.history.go(-1) |  | 
    self.driver.execute_script("window.history.go(-1)")
    # 28 | click | linkText=ดูทั้งหมด |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 29 | storeWindowHandle | root |  | 
    self.driver.find_element(By.LINK_TEXT, "ดูทั้งหมด").click()
    # 30 | selectWindow | handle=${win5733} |  | 
    self.vars["win5733"] = self.wait_for_window(2000)
    # 31 | close |  |  | 
    self.vars["root"] = self.driver.current_window_handle
    # 32 | selectWindow | handle=${root} |  | 
    self.driver.switch_to.window(self.vars["win5733"])
    # 33 | click | linkText=อีเมล |  | 
    self.driver.close()
    # 34 | selectWindow | handle=${win8643} |  | 
    self.driver.switch_to.window(self.vars["root"])
    # 35 | close |  |  | 
    self.vars["window_handles"] = self.driver.window_handles
    # 36 | selectWindow | handle=${root} |  | 
    self.driver.find_element(By.LINK_TEXT, "อีเมล").click()
    # 37 | click | css=.bt-contact > .btn |  | 
    self.vars["win8643"] = self.wait_for_window(2000)
    # 38 | selectWindow | handle=${win1382} |  | 
    self.driver.switch_to.window(self.vars["win8643"])
    # 39 | close |  |  | 
    self.driver.close()
    # 40 | selectWindow | handle=${root} |  | 
    self.driver.switch_to.window(self.vars["root"])
    self.vars["window_handles"] = self.driver.window_handles
    self.driver.find_element(By.CSS_SELECTOR, ".bt-contact > .btn").click()
    self.vars["win1382"] = self.wait_for_window(2000)
    self.driver.switch_to.window(self.vars["win1382"])
    self.driver.close()
    self.driver.switch_to.window(self.vars["root"])
  
