# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestPromotionsTH():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_promotionsTH(self):
    # Test name: Promotions TH
    # Step # | name | target | value | comment
    # 1 | open | https://demo.irplus.in.th/Listed/susco/homepage.asp |  | 
    self.driver.get("https://demo.irplus.in.th/Listed/susco/homepage.asp")
    # 2 | setWindowSize | 1936x1056 |  | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 4 | click | linkText=TH |  | 
    self.driver.find_element(By.LINK_TEXT, "TH").click()
    # 5 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 6 | click | linkText=ส่งเสริมการขาย |  | 
    self.driver.find_element(By.LINK_TEXT, "ส่งเสริมการขาย").click()
    # 7 | click | id=slideout-bt |  | 
    self.driver.find_element(By.ID, "slideout-bt").click()
    # 8 | click | linkText=ยอมรับ |  | 
    self.driver.find_element(By.LINK_TEXT, "ยอมรับ").click()
    time.sleep(2)
    # 9 | click | linkText=รายละเอียด |  | 
    self.driver.find_element(By.LINK_TEXT, "รายละเอียด").click()
    time.sleep(2)
    # 10 | click | css=#Modal-89 .dismiss-modal |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#Modal-89 .dismiss-modal").click()
    time.sleep(2)
    # 11 | click | css=.col-xl-4:nth-child(2) .btn-promotion |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-xl-4:nth-child(2) .btn-promotion").click()
    time.sleep(2)
    # 12 | click | css=#Modal-88 .dismiss-modal |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#Modal-88 .dismiss-modal").click()
    time.sleep(2)
    # 13 | click | css=.col-xl-4:nth-child(3) .btn-promotion |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".col-xl-4:nth-child(3) .btn-promotion").click()
    time.sleep(2)
    # 14 | click | css=#Modal-86 .dismiss-modal |  | 
    self.driver.find_element(By.CSS_SELECTOR, "#Modal-86 .dismiss-modal").click()
    time.sleep(2)
  
