# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRequestAlertsEN():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_requestAlertsEN(self):
    # Test name: Request Alerts EN
    # Step # | name | target | value | comment
    # 1 | open | https://demo.irplus.in.th/Listed/susco/homepage.asp |  | 
    self.driver.get("https://demo.irplus.in.th/Listed/susco/homepage.asp")
    # 2 | setWindowSize | 1936x1056 |  | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 4 | click | linkText=EN |  | 
    self.driver.find_element(By.LINK_TEXT, "EN").click()
    # 5 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 6 | click | linkText=INVESTOR RELATIONS |  | 
    self.driver.find_element(By.LINK_TEXT, "INVESTOR RELATIONS").click()
    # 7 | mouseOver | css=li:nth-child(9) > .dropdown-item |  | 
    element = self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(9) > .dropdown-item")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | click | css=li:nth-child(9) li:nth-child(1) > .dropdown-item |  | 
    self.driver.find_element(By.CSS_SELECTOR, "li:nth-child(9) li:nth-child(1) > .dropdown-item").click()
    # 9 | click | id=email |  | 
    self.driver.find_element(By.ID, "email").click()
    # 10 | type | id=email | Test@tt.tt | 
    self.driver.find_element(By.ID, "email").send_keys("Test@tt.tt")
    # 11 | click | css=.accept-terms |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".accept-terms").click()
    # 12 | selectFrame | index=0 |  | 
    self.driver.switch_to.frame(0)
    # 13 | click | css=.recaptcha-checkbox-border |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    # 14 | selectFrame | relative=parent |  | 
    self.driver.switch_to.default_content()
    # 15 | click | id=subscribe |  | 
    self.driver.find_element(By.ID, "subscribe").click()
  
