# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestRequestInquiryTH():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_requestInquiryTH(self):
    # Test name: Request Inquiry TH
    # Step # | name | target | value | comment
    # 1 | open | https://demo.irplus.in.th/Listed/susco/homepage.asp |  | 
    self.driver.get("https://demo.irplus.in.th/Listed/susco/homepage.asp")
    # 2 | setWindowSize | 1936x1056 |  | 
    self.driver.set_window_size(1936, 1056)
    # 3 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 4 | click | linkText=TH |  | 
    self.driver.find_element(By.LINK_TEXT, "TH").click()
    # 5 | click | css=.fa |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".fa").click()
    # 6 | click | linkText=นักลงทุนสัมพันธ์ |  | 
    self.driver.find_element(By.LINK_TEXT, "นักลงทุนสัมพันธ์").click()
    # 7 | mouseOver | linkText=สอบถามข้อมูล |  | 
    element = self.driver.find_element(By.LINK_TEXT, "สอบถามข้อมูล")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 8 | click | linkText=ฝากคำถาม |  | 
    self.driver.find_element(By.LINK_TEXT, "ฝากคำถาม").click()
    # 9 | click | id=full_name |  | 
    self.driver.find_element(By.ID, "full_name").click()
    # 10 | click | css=.banner-sub-ir > .container |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".banner-sub-ir > .container").click()
    # 11 | click | css=.banner-sub-ir-2 |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".banner-sub-ir-2").click()
    # 12 | type | id=full_name | Test TH | 
    self.driver.find_element(By.ID, "full_name").send_keys("Test TH")
    # 13 | click | id=phone |  | 
    self.driver.find_element(By.ID, "phone").click()
    # 14 | type | id=phone | 0000000000 | 
    self.driver.find_element(By.ID, "phone").send_keys("0000000000")
    # 15 | click | id=email |  | 
    self.driver.find_element(By.ID, "email").click()
    # 16 | type | id=email | Test@tt.tt | 
    self.driver.find_element(By.ID, "email").send_keys("Test@tt.tt")
    # 17 | click | id=detail |  | 
    self.driver.find_element(By.ID, "detail").click()
    # 18 | type | id=detail | Test TH | 
    self.driver.find_element(By.ID, "detail").send_keys("Test TH")
    # 19 | click | id=chkboxconsent |  | 
    self.driver.find_element(By.ID, "chkboxconsent").click()
    # 20 | selectFrame | index=0 |  | 
    self.driver.switch_to.frame(0)
    # 21 | click | css=.recaptcha-checkbox-border |  | 
    self.driver.find_element(By.CSS_SELECTOR, ".recaptcha-checkbox-border").click()
    # 22 | selectFrame | relative=parent |  | 
    self.driver.switch_to.default_content()
    # 23 | click | id=subscribe |  | 
    self.driver.find_element(By.ID, "subscribe").click()
  
